### PR TITLE
Erweiterte den Mimetypes List

### PR DESCRIPTION
**Pull request by DavidGutknecht**

### CODE REVIEW

**Comment by col-panic** [comment]
Is there a specific bug or reason on why you are extending the list?

**Comment by DavidGutknecht** [comment]
It is not linked to any bug. I just had to set the list for another project, and I was thinking it could be also usefull here.

**Comment by col-panic** [comment]
I think when using this patch we should not use an array anymore for resolving the resp. mimetypes, but rather a Map. The pro of the current implementation is, that it is fast enough (with these few values) to be backed by an array. So if you could extend your patch to back it with a map that would be a way to go.

**Comment by col-panic** [comment]
only used in document management; in all othere relevant areas we use an external Mime tooling

**Pull request closed without merging**
