### PR TITLE
[9096] Added setting to change Handbook url in Iatrix Hilfe > Handbuch

### PR DESCRIPTION
**Pull request by jamda**

### CODE REVIEW

**Comment by col-panic** [comment]
I am sorry, have a look here https://github.com/elexis/elexis-3-core/pull/203/files - theres no difference shown between the source files. It just shows to remove everything and then add yours. I can't determine the diff this way. :(

**Comment by jamda** [comment]
Take a look to the last commit please. [Last commit](https://github.com/elexis/elexis-3-core/pull/203/commits/9e08f28b26b898da49611a7d830b82534a65792e). It's not perfect but you can see where i changed Something.

**Comment by jamda** [comment]
The link is actually the last commit of this PR. With title 
[9096] Added setting to change Handbook url in Iatrix Hilfe > Handbuch.

**Comment by col-panic** [comment]
In this commit I do see only translation changes, but no actual code changes - whats the deal with GlobalActions?

**Comment by jamda** [comment]
In GlobalActions there is a little change. With this commit there is the ability for the user to change the link to Handbuch in Préférences > Iatrix Wiki Hilfe > Handbuch to the URL they want. And one error message if the link is bad formatted. That's why i had to change the other files so the error message displays in 3 different tongues an error message saying they should put a message from type https://www.google.ch.

**Comment by jamda** [comment]
By default it points to https://wiki.elexis.info/Deutsches_Handbuch_3.1

**Comment by jamda** [comment]
in GlobalActions only lines 191-192 and 198-199 have changed

**Pull request closed without merging**
