### PR TITLE
[8837] Open manual via default browser+added a field Handbook in Iatrix preferences

### PR DESCRIPTION
**Pull request by jamda**

### CODE REVIEW

**Comment by ngiger** [comment]
I tried the changes locally under Linux, where it braeks with
<pre>
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7d6073537c, pid=15518, tid=0x00007f7e3fc65700
#
# JRE version: OpenJDK Runtime Environment (8.0_151-b12) (build 1.8.0_151-8u151-b12-1~deb9u1-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libgdk-x11-2.0.so.0+0x4e37c]  gdk_display_open+0x5c
</pre>
But this is a general problem, which has to be resolved in another ticket.

**Comment by jamda** [comment]
Not sure it is a general problem. The code i provided i guess is not the cross-platform way to do it. I should be able to provide an alternative. Let me know what you think.

**Comment by jamda** [comment]
A little change that should work.

**Comment by col-panic** [comment]
Using your branch I face a HeadlessException due to the fact, that the system property `-Djava.awt.headless=true` is set. This is the case for OS X and Linux. After removing the property the page is correctly opened in an external browser. 

I see however, that the "Iatrix Hilfe" View does exactly the same; opening the resp. wiki page within Elexis.

Niklaus, do you know about any reason we added the awt.headless property to the run configuration? There seems to be other code depending on awt.Desktop, I am not sure, however, whether this code is really used.

@jamda please remove the headless system property from the resp. product files in addition.

**Comment by ngiger** [comment]
I get the execption even when I start Elexis with the parameters `-vmargs -Djava.awt.headless=false`. And I do not see any place in elexis-3-core where the java.awt.headless is set.

If I use F1 from Iatrix-Hilfe I see an embedded window, but it shows only `Unacceptable TLS certificate`

**Comment by jamda** [comment]
I couldn't find the files you were talking about to set `-Djava.awt.headless=false`.

**Comment by col-panic** [comment]
It is set in the Elexis.product file.

**Pull request merged**
